name: Build & Deploy Lambda function

env:
  ARTIFACT_NAME: csye6225-lambda-${{ github.sha }}.zip
  AWS_REGION: us-east-1

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lambda_ci_cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: |
          echo "${{ env.ARTIFACT_NAME }}"
          pwd
          mvn clean package shade:shade
          pwd
          ls -al target


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: upload jar and overwrite into S3
        run: |
          aws s3 cp target/serverless-1.0-SNAPSHOT.jar s3://lambda.dev.zhijie-li.me

      - name: deploy
        run: |
#          aws lambda update-function-code --function-name=send_verification_email --zip-file=fileb://target/serverless-1.0-SNAPSHOT.jar
          aws lambda update-function-code --function-name=send_verification_email --s3-bucket=lambda.dev.zhijie-li.me --s3-key=serverless-1.0-SNAPSHOT.jar

